# Generated by Django 5.1.3 on 2024-11-11 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_receipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receipe',
            new_name='Recipe',
        ),
    ]
