# Generated by Django 5.1.3 on 2024-11-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_receipe_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='receipe_description',
            new_name='recipe_description',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='receipe_name',
            new_name='recipe_name',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='receipe_image',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(default='d', upload_to='recipes/'),
            preserve_default=False,
        ),
    ]
